In [1]:
import os
import pandas as pd
import numpy as np
!pip install pybaseball

Requirement already satisfied: pybaseball in c:\users\daniel\anaconda3\lib\site-packages (2.2.7)
Requirement already satisfied: numpy>=1.13.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (1.26.4)
Requirement already satisfied: pandas>=1.0.3 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (2.2.2)
Requirement already satisfied: beautifulsoup4>=4.4.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (4.12.3)
Requirement already satisfied: requests>=2.18.1 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (2.32.3)
Requirement already satisfied: lxml>=4.2.1 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (5.2.1)
Requirement already satisfied: pyarrow>=1.0.1 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (16.1.0)
Requirement already satisfied: pygithub>=1.51 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (2.5.0)
Requirement already satisfied: scipy>=1.4.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (1.13.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (3.9.2)
Requirement already satisfied: tqdm>=4.50.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (4.66.5)
Requirement already satisfied: attrs>=20.3.0 in c:\users\daniel\anaconda3\lib\site-packages (from pybaseball) (23.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\daniel\anaconda3\lib\site-packages (from beautifulsoup4>=4.4.0->pybaseball) (2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\daniel\anaconda3\lib\site-packages (from matplotlib>=2.0.0->pybaseball) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\daniel\anaconda3\lib\site-packages (from pandas>=1.0.3->pybaseball) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\daniel\anaconda3\lib\site-packages (from pandas>=1.0.3->pybaseball) (2023.3)
Requirement already satisfied: pynacl>=1.4.0 in c:\users\daniel\anaconda3\lib\site-packages (from pygithub>=1.51->pybaseball) (1.5.0)
Requirement already satisfied: pyjwt>=2.4.0 in c:\users\daniel\anaconda3\lib\site-packages (from pyjwt[crypto]>=2.4.0->pygithub>=1.51->pybaseball) (2.8.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\daniel\anaconda3\lib\site-packages (from pygithub>=1.51->pybaseball) (4.11.0)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\daniel\anaconda3\lib\site-packages (from pygithub>=1.51->pybaseball) (2.2.3)
Requirement already satisfied: Deprecated in c:\users\daniel\anaconda3\lib\site-packages (from pygithub>=1.51->pybaseball) (1.2.14)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\daniel\anaconda3\lib\site-packages (from requests>=2.18.1->pybaseball) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\daniel\anaconda3\lib\site-packages (from requests>=2.18.1->pybaseball) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\daniel\anaconda3\lib\site-packages (from requests>=2.18.1->pybaseball) (2024.8.30)
Requirement already satisfied: colorama in c:\users\daniel\anaconda3\lib\site-packages (from tqdm>=4.50.0->pybaseball) (0.4.6)
Requirement already satisfied: cryptography>=3.4.0 in c:\users\daniel\anaconda3\lib\site-packages (from pyjwt[crypto]>=2.4.0->pygithub>=1.51->pybaseball) (43.0.0)
Requirement already satisfied: cffi>=1.4.1 in c:\users\daniel\anaconda3\lib\site-packages (from pynacl>=1.4.0->pygithub>=1.51->pybaseball) (1.17.1)
Requirement already satisfied: six>=1.5 in c:\users\daniel\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.0.0->pybaseball) (1.16.0)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\daniel\anaconda3\lib\site-packages (from Deprecated->pygithub>=1.51->pybaseball) (1.14.1)
Requirement already satisfied: pycparser in c:\users\daniel\anaconda3\lib\site-packages (from cffi>=1.4.1->pynacl>=1.4.0->pygithub>=1.51->pybaseball) (2.21)

In [3]:
from pybaseball import batting_stats

In [5]:
START = 2002
END = 2022

In [7]:
batting = batting_stats(START,END,qual=200)

In [9]:
batting.to_csv("batting.csv")

In [11]:
pd.read_csv('batting.csv')

,Unnamed: 0,IDfg,Season,Name,Team,Age,G,AB,PA,H,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,0,1109,2002,Barry Bonds,SFG,37,143,403,612,149,...,NaN,NaN,NaN,0,0.127,0.191,NaN,NaN,NaN,12.7
1,1,1109,2004,Barry Bonds,SFG,39,147,373,617,135,...,NaN,NaN,NaN,0,0.124,0.164,NaN,NaN,NaN,11.9
2,8,15640,2022,Aaron Judge,NYY,30,157,570,696,177,...,118.4,246.0,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
3,2,1109,2003,Barry Bonds,SFG,38,130,390,550,133,...,NaN,NaN,NaN,0,0.135,0.223,NaN,NaN,NaN,10.2
4,15,13611,2018,Mookie Betts,BOS,25,136,520,614,180,...,110.6,217.0,0.500,434,0.220,0.270,NaN,NaN,NaN,10.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7109,7042,9272,2018,Chris Davis,BAL,32,128,470,522,79,...,111.8,113.0,0.401,282,0.174,0.316,NaN,NaN,NaN,-2.6
7110,6535,45,2012,Rod Barajas,PIT,36,104,321,361,66,...,NaN,0.0,NaN,0,0.147,0.258,NaN,NaN,NaN,-2.6
7111,6673,319,2011,Adam Dunn,CHW,31,122,415,496,66,...,NaN,0.0,NaN,0,0.169,0.295,NaN,NaN,NaN,-2.9
7112,6988,620,2002,Neifi Perez,KCR,29,145,554,585,131,...,NaN,NaN,NaN,0,0.130,0.187,NaN,NaN,NaN,-2.9
7113,978,2113,2008,Ryan Doumit,PIT,27,116,431,465,137,...,NaN,0.0,NaN,0,0.144,0.231,NaN,NaN,NaN,-3.1

In [13]:
batting = batting.groupby("IDfg",group_keys=False).filter(lambda x:x.shape[0]>1)

In [15]:
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,1109,2002,Barry Bonds,SFG,37,143,403,612,149,70,...,NaN,NaN,NaN,0,0.127,0.191,NaN,NaN,NaN,12.7
1,1109,2004,Barry Bonds,SFG,39,147,373,617,135,60,...,NaN,NaN,NaN,0,0.124,0.164,NaN,NaN,NaN,11.9
8,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246.0,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
2,1109,2003,Barry Bonds,SFG,38,130,390,550,133,65,...,NaN,NaN,NaN,0,0.135,0.223,NaN,NaN,NaN,10.2
15,13611,2018,Mookie Betts,BOS,25,136,520,614,180,96,...,110.6,217.0,0.500,434,0.220,0.270,NaN,NaN,NaN,10.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7042,9272,2018,Chris Davis,BAL,32,128,470,522,79,51,...,111.8,113.0,0.401,282,0.174,0.316,NaN,NaN,NaN,-2.6
6535,45,2012,Rod Barajas,PIT,36,104,321,361,66,44,...,NaN,0.0,NaN,0,0.147,0.258,NaN,NaN,NaN,-2.6
6673,319,2011,Adam Dunn,CHW,31,122,415,496,66,39,...,NaN,0.0,NaN,0,0.169,0.295,NaN,NaN,NaN,-2.9
6988,620,2002,Neifi Perez,KCR,29,145,554,585,131,104,...,NaN,NaN,NaN,0,0.130,0.187,NaN,NaN,NaN,-2.9
978,2113,2008,Ryan Doumit,PIT,27,116,431,465,137,88,...,NaN,0.0,NaN,0,0.144,0.231,NaN,NaN,NaN,-3.1

In [17]:
##CREATING THE ML TARGET

In [19]:
def next_season(player):
    player = player.sort_values("Season")
    player["Next WAR"] = player["WAR"].shift(-1)
    return player

In [21]:
batting = batting.groupby(by="IDfg",group_keys=False).apply(next_season)
batting

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\440358122.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  batting = batting.groupby(by="IDfg",group_keys=False).apply(next_season)

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR,Next WAR
5562,1,2006,Alfredo Amezaga,FLA,28,132,334,378,87,72,...,NaN,NaN,0,0.188,0.256,NaN,NaN,NaN,1.1,2.0
5006,1,2007,Alfredo Amezaga,FLA,29,133,400,448,105,80,...,0.0,NaN,0,0.175,0.227,NaN,NaN,NaN,2.0,1.2
5252,1,2008,Alfredo Amezaga,FLA,30,125,311,337,82,61,...,0.0,NaN,0,0.178,0.244,NaN,NaN,NaN,1.2,NaN
1169,2,2002,Garret Anderson,ANA,30,158,638,678,195,107,...,NaN,NaN,0,0.137,0.232,NaN,NaN,NaN,3.7,5.1
864,2,2003,Garret Anderson,ANA,31,159,638,673,201,119,...,NaN,NaN,0,0.164,0.252,NaN,NaN,NaN,5.1,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6002,24655,2022,Owen Miller,CLE,25,130,424,472,103,70,...,106.0,0.312,340,0.188,0.266,NaN,NaN,NaN,0.7,NaN
4881,26197,2021,Andrew Vaughn,CHW,23,127,417,469,98,61,...,149.0,0.464,321,0.185,0.285,NaN,NaN,NaN,-0.4,-0.5
3377,26197,2022,Andrew Vaughn,CHW,24,134,510,555,138,92,...,203.0,0.484,419,0.201,0.291,NaN,NaN,NaN,-0.5,NaN
6620,27506,2021,Ha-seong Kim,SDP,25,117,267,298,54,32,...,64.0,0.318,201,0.216,0.303,NaN,NaN,NaN,0.5,3.6
4396,27506,2022,Ha-seong Kim,SDP,26,150,517,582,130,87,...,137.0,0.323,424,0.205,0.276,NaN,NaN,NaN,3.7,NaN

In [23]:
batting[['Name','Season','WAR','Next WAR']]

                 Name  Season  WAR  Next WAR
5562  Alfredo Amezaga    2006  1.1       2.0
5006  Alfredo Amezaga    2007  2.0       1.2
5252  Alfredo Amezaga    2008  1.2       NaN
1169  Garret Anderson    2002  3.7       5.1
864   Garret Anderson    2003  5.1       0.8
...               ...     ...  ...       ...
6002      Owen Miller    2022  0.7       NaN
4881    Andrew Vaughn    2021 -0.2      -0.5
3377    Andrew Vaughn    2022 -0.5       NaN
6620     Ha-seong Kim    2021  0.4       3.6
4396     Ha-seong Kim    2022  3.6       NaN

[6754 rows x 4 columns]

In [25]:
#CLEANING THE DATA

In [27]:
null_count = batting.apply(pd.isnull).sum()
null_count

IDfg           0
Season         0
Name           0
Team           0
Age            0
            ...
xBA         6754
xSLG        6754
xwOBA       6754
L-WAR          0
Next WAR    1179
Length: 321, dtype: int64

In [29]:
complete_cols = list(batting.columns[null_count == 0])

In [31]:
complete_cols

['IDfg',
 'Season',
 'Name',
 'Team',
 'Age',
 'G',
 'AB',
 'PA',
 'H',
 '1B',
 '2B',
 '3B',
 'HR',
 'R',
 'RBI',
 'BB',
 'IBB',
 'SO',
 'HBP',
 'SF',
 'SH',
 'GDP',
 'SB',
 'CS',
 'AVG',
 'GB',
 'FB',
 'LD',
 'IFFB',
 'Pitches',
 'Balls',
 'Strikes',
 'IFH',
 'BU',
 'BUH',
 'BB%',
 'K%',
 'BB/K',
 'OBP',
 'SLG',
 'OPS',
 'ISO',
 'BABIP',
 'GB/FB',
 'LD%',
 'GB%',
 'FB%',
 'IFFB%',
 'HR/FB',
 'IFH%',
 'BUH%',
 'wOBA',
 'wRAA',
 'wRC',
 'Bat',
 'Rep',
 'Pos',
 'RAR',
 'WAR',
 'Dol',
 'Spd',
 'wRC+',
 'WPA',
 '-WPA',
 '+WPA',
 'RE24',
 'REW',
 'pLI',
 'PH',
 'WPA/LI',
 'Clutch',
 'FB% (Pitch)',
 'FBv',
 'SL%',
 'SLv',
 'CB%',
 'CBv',
 'CH%',
 'CHv',
 'wFB',
 'wSL',
 'wCB',
 'wCH',
 'wFB/C',
 'wSL/C',
 'wCB/C',
 'wCH/C',
 'O-Swing%',
 'Z-Swing%',
 'Swing%',
 'O-Contact%',
 'Z-Contact%',
 'Contact%',
 'Zone%',
 'F-Strike%',
 'SwStr%',
 'BsR',
 'Def',
 'wSB',
 'UBR',
 'Age Rng',
 'Off',
 'Lg',
 'wGDP',
 'Pull%',
 'Cent%',
 'Oppo%',
 'Soft%',
 'Med%',
 'Hard%',
 'TTO%',
 'AVG+',
 'BB%+',
 'K%+',
 'OBP+',
 'SLG+',
 'ISO+',
 'BABIP+',
 'LD+%',
 'GB%+',
 'FB%+',
 'HR/FB%+',
 'Pull%+',
 'Cent%+',
 'Oppo%+',
 'Soft%+',
 'Med%+',
 'Hard%+',
 'Events',
 'CStr%',
 'CSW%',
 'L-WAR']

In [33]:
batting = batting[complete_cols + ["Next WAR"]].copy()
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Cent%+,Oppo%+,Soft%+,Med%+,Hard%+,Events,CStr%,CSW%,L-WAR,Next WAR
5562,1,2006,Alfredo Amezaga,FLA,28,132,334,378,87,72,...,107,113,143,109,63,0,0.188,0.256,1.1,2.0
5006,1,2007,Alfredo Amezaga,FLA,29,133,400,448,105,80,...,101,112,109,113,75,0,0.175,0.227,2.0,1.2
5252,1,2008,Alfredo Amezaga,FLA,30,125,311,337,82,61,...,101,101,123,111,64,0,0.178,0.244,1.2,NaN
1169,2,2002,Garret Anderson,ANA,30,158,638,678,195,107,...,91,80,65,97,129,0,0.137,0.232,3.7,5.1
864,2,2003,Garret Anderson,ANA,31,159,638,673,201,119,...,101,80,90,99,109,0,0.164,0.252,5.1,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6002,24655,2022,Owen Miller,CLE,25,130,424,472,103,70,...,111,97,131,100,83,340,0.188,0.266,0.7,NaN
4881,26197,2021,Andrew Vaughn,CHW,23,127,417,469,98,61,...,104,116,84,99,110,321,0.185,0.285,-0.4,-0.5
3377,26197,2022,Andrew Vaughn,CHW,24,134,510,555,138,92,...,106,111,94,100,104,419,0.201,0.291,-0.5,NaN
6620,27506,2021,Ha-seong Kim,SDP,25,117,267,298,54,32,...,99,59,137,96,88,201,0.216,0.303,0.5,3.6
4396,27506,2022,Ha-seong Kim,SDP,26,150,517,582,130,87,...,104,71,117,100,90,424,0.205,0.276,3.7,NaN

In [35]:
batting.columns[batting.dtypes == "object"]

Index(['Name', 'Team', 'Dol', 'Age Rng'], dtype='object')

In [37]:
batting['Age Rng']

5562    28 - 28
5006    29 - 29
5252    30 - 30
1169    30 - 30
864     31 - 31
         ...
6002    25 - 25
4881    23 - 23
3377    24 - 24
6620    25 - 25
4396    26 - 26
Name: Age Rng, Length: 6754, dtype: object

In [39]:
del batting['Age Rng']

In [41]:
batting[['Dol']]
del batting['Dol']

In [43]:
batting ["Team code"] = batting["Team"].astype("category").cat.codes

In [45]:
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Oppo%+,Soft%+,Med%+,Hard%+,Events,CStr%,CSW%,L-WAR,Next WAR,Team code
5562,1,2006,Alfredo Amezaga,FLA,28,132,334,378,87,72,...,113,143,109,63,0,0.188,0.256,1.1,2.0,12
5006,1,2007,Alfredo Amezaga,FLA,29,133,400,448,105,80,...,112,109,113,75,0,0.175,0.227,2.0,1.2,12
5252,1,2008,Alfredo Amezaga,FLA,30,125,311,337,82,61,...,101,123,111,64,0,0.178,0.244,1.2,NaN,12
1169,2,2002,Garret Anderson,ANA,30,158,638,678,195,107,...,80,65,97,129,0,0.137,0.232,3.7,5.1,1
864,2,2003,Garret Anderson,ANA,31,159,638,673,201,119,...,80,90,99,109,0,0.164,0.252,5.1,0.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6002,24655,2022,Owen Miller,CLE,25,130,424,472,103,70,...,97,131,100,83,340,0.188,0.266,0.7,NaN,9
4881,26197,2021,Andrew Vaughn,CHW,23,127,417,469,98,61,...,116,84,99,110,321,0.185,0.285,-0.4,-0.5,7
3377,26197,2022,Andrew Vaughn,CHW,24,134,510,555,138,92,...,111,94,100,104,419,0.201,0.291,-0.5,NaN,7
6620,27506,2021,Ha-seong Kim,SDP,25,117,267,298,54,32,...,59,137,96,88,201,0.216,0.303,0.5,3.6,26
4396,27506,2022,Ha-seong Kim,SDP,26,150,517,582,130,87,...,71,117,100,90,424,0.205,0.276,3.7,NaN,26

In [47]:
batting_full = batting.copy()
batting = batting.dropna().copy()

In [49]:
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

In [51]:
rr = Ridge(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(estimator= rr,n_features_to_select=20,direction='forward',cv=split,n_jobs=4)

In [53]:
removed_columns = ["Name","Team","IDfg","Next WAR","Season"]
required_columns = batting.columns[~batting.columns.isin(removed_columns)]
batting[required_columns]

,Age,G,AB,PA,H,1B,2B,3B,HR,R,...,Cent%+,Oppo%+,Soft%+,Med%+,Hard%+,Events,CStr%,CSW%,L-WAR,Team code
5562,28,132,334,378,87,72,9,3,3,42,...,107,113,143,109,63,0,0.188,0.256,1.1,12
5006,29,133,400,448,105,80,14,9,2,46,...,101,112,109,113,75,0,0.175,0.227,2.0,12
1169,30,158,638,678,195,107,56,3,29,93,...,91,80,65,97,129,0,0.137,0.232,3.7,1
864,31,159,638,673,201,119,49,4,29,80,...,101,80,90,99,109,0,0.164,0.252,5.1,1
2569,32,112,442,475,133,98,20,1,14,57,...,103,75,78,106,98,0,0.176,0.270,0.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1914,20,70,281,308,81,51,18,5,7,53,...,114,98,100,106,90,245,0.143,0.217,2.4,31
5875,24,85,267,293,53,28,10,1,14,28,...,96,88,92,88,123,159,0.172,0.316,0.7,19
7032,24,60,191,202,39,27,8,0,4,17,...,111,125,84,111,90,138,0.180,0.296,-0.9,9
4881,23,127,417,469,98,61,22,0,15,56,...,104,116,84,99,110,321,0.185,0.285,-0.4,7
6620,25,117,267,298,54,32,12,2,8,27,...,99,59,137,96,88,201,0.216,0.303,0.5,26

In [55]:
#TIME TO SCALE THE DATA UP IN ORDER PREVENT OVERFITTING OR MULTICOLLINEARITY

In [57]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
scaler = MinMaxScaler()

In [61]:
required_columns

Index(['Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR', 'R',
       ...
       'Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+', 'Events', 'CStr%',
       'CSW%', 'L-WAR', 'Team code'],
      dtype='object', length=127)

In [63]:
batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34615385 0.38461538 0.42307692 ... 0.19230769 0.15384615 0.23076923]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.73504274 0.74358974 0.95726496 ... 0.11965812 0.69230769 0.60683761]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.31294964 0.43165468 0.85971223 ... 0.0557554  0.46223022 0.19244604]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.30795848 0.42906574 0.82698962 ... 0.00346021 0.46539792 0.16955017]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.24568966 0.32327586 0.7112069  ... 0.0387931  0.29310345 0.10344828]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.27830189 0.31603774 0.44339623 ... 0.06603774 0.22641509 0.08962264]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.15517241 0.24137931 0.96551724 ... 0.13793103 0.37931034 0.20689655]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.13043478 0.39130435 0.13043478 ... 0.         0.         0.08695652]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.05084746 0.03389831 0.49152542 ... 0.06779661 0.25423729 0.13559322]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2406015  0.27067669 0.62406015 ... 0.05263158 0.34586466 0.12781955]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.07432432 0.14864865 0.77702703 ... 0.06756757 0.27027027 0.17567568]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.13478261 0.14347826 0.12173913 ... 0.03043478 0.16956522 0.08695652]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.03333333 0.         0.09166667 ... 0.         0.         0.00833333]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.17674419 0.20465116 0.33488372 ... 0.21395349 0.43255814 0.29302326]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.09677419 0.12903226 0.         ... 0.03225806 0.19354839 0.12903226]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.0625 0.3125 0.625  ... 0.0625 0.3125 0.1875]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.29166667 0.16666667 0.         ... 0.         0.         0.08333333]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.15625 0.125   0.34375 ... 0.21875 0.4375  0.1875 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.25641026 0.16666667 0.07692308 ... 0.02564103 0.01282051 0.07692308]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.5        0.29166667 0.16666667 ... 0.         0.04166667 0.04166667]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.30107527 0.34677419 0.48924731 ... 0.12365591 0.30107527 0.14247312]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.27340824 0.34831461 0.75655431 ... 0.06367041 0.3670412  0.23970037]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2260274  0.38356164 0.83561644 ... 0.09589041 0.34246575 0.1369863 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2        0.2        0.23076923 ... 0.06153846 0.06153846 0.24615385]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.31749049 0.41064639 0.58174905 ... 0.05969582 0.46235741 0.2243346 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.25358852 0.33971292 0.42902711 ... 0.04625199 0.37001595 0.16746411]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34420772 0.43541944 0.66045273 ... 0.06591212 0.50066578 0.25299601]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.28070175 0.19298246 0.15789474 ... 0.0877193  0.21052632 0.12280702]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.19101124 0.20224719 0.01123596 ... 0.         0.         0.03370787]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.10526316 0.21052632 0.02631579 ... 0.         0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.19892473 0.24731183 0.55376344 ... 0.06989247 0.29569892 0.13978495]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.30452675 0.32098765 0.50205761 ... 0.20576132 0.37860082 0.28806584]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.31325301 0.31325301 0.01204819 ... 0.06024096 0.07228916 0.48192771]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.42553191 0.42553191 0.63829787 ... 0.28723404 0.42553191 0.26595745]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.21287129 0.18811881 0.10148515 ... 0.10148515 0.22524752 0.16831683]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.28787879 0.27272727 0.28282828 ... 0.50505051 0.38888889 0.45454545]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34920635 0.33333333 0.37301587 ... 0.19047619 0.35714286 0.23809524]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.17985612 0.23021583 0.55395683 ... 0.17266187 0.32374101 0.24460432]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.08333333 0.1468254  0.49206349 ... 0.16269841 0.29365079 0.26190476]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.44827586 0.43678161 0.54022989 ... 0.36781609 0.40229885 0.27586207]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.60330579 0.54545455 0.36363636 ... 0.69421488 0.49586777 0.43801653]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.39310345 0.37241379 0.52413793 ... 0.25517241 0.46206897 0.57241379]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.08287293 0.04972376 0.33977901 ... 0.2320442  0.26243094 0.1961326 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.36206897 0.4137931  0.63793103 ... 0.27586207 0.37068966 0.70689655]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.53932584 0.47191011 0.35955056 ... 0.58426966 0.50561798 0.4494382 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])
C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\1389868503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.5037594  0.4962406  0.2556391  ... 0.59398496 0.52631579 0.09774436]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  batting.loc[:,required_columns] = scaler.fit_transform(batting[required_columns])

In [65]:
batting = batting.describe().copy()
batting

,IDfg,Season,Age,G,AB,PA,H,1B,2B,3B,...,Oppo%+,Soft%+,Med%+,Hard%+,Events,CStr%,CSW%,L-WAR,Next WAR,Team code
count,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,...,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000,5575.000000
mean,5366.785830,2011.163229,0.360600,0.652755,0.478666,0.480943,0.365973,0.290481,0.399279,0.103459,...,0.403164,0.410923,0.511026,0.478646,0.172991,0.498932,0.545898,0.322040,1.793130,0.474128
std,5133.255295,5.612014,0.147476,0.255929,0.242481,0.262290,0.182585,0.138786,0.171732,0.105891,...,0.131213,0.121082,0.130359,0.133992,0.273858,0.137180,0.120701,0.122153,1.981035,0.305105
min,1.000000,2002.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.100000,0.000000
25%,1131.500000,2006.000000,0.269231,0.478632,0.275180,0.257785,0.211207,0.179245,0.258621,0.043478,...,0.315789,0.331461,0.420290,0.387755,0.000000,0.408511,0.466960,0.234177,0.350000,0.205882
50%,3531.000000,2011.000000,0.346154,0.709402,0.505396,0.508651,0.370690,0.283019,0.379310,0.086957,...,0.398496,0.404494,0.507246,0.489796,0.000000,0.493617,0.546256,0.303797,1.500000,0.470588
75%,9015.000000,2016.000000,0.461538,0.871795,0.688849,0.710208,0.508621,0.391509,0.517241,0.130435,...,0.488722,0.483146,0.594203,0.564626,0.346411,0.591489,0.625551,0.392405,2.900000,0.735294
max,27506.000000,2021.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.900000,1.000000

In [67]:
sfs.fit(batting[required_columns],batting["Next WAR"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=Ridge(alpha=1), n_features_to_select=20,
                          n_jobs=4)

In [69]:
predictors = list(required_columns[sfs.get_support()])

In [71]:
#CREATING A BACK TEST FUNCTION THAT HELPS CREATE PREDICTIONS

In [73]:
def backtest(data, model, predictors, start=5, step = 1):
    all_predictions = []
    years = sorted(data['Season'].unique())
    
    for i in range (start, len(years), step):
        current_year = years[i]
        train = data[data['Season'] < current_year]
        test = data[data['Season'] == current_year]
        train[predictors] = train[predictors].fillna(train[predictors].mean())

        model.fit(train[predictors],train["Next WAR"])
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([preds,test["Next WAR"]], axis=1)
        combined.columns = ["Actual","Predicted"]
        
        all_predictions.append(combined)
        return pd.concat(all_predictions)

In [75]:
predictions = backtest(batting, rr, predictors)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\863576076.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[predictors] = train[predictors].fillna(train[predictors].mean())

In [77]:
predictions

       Actual  Predicted
75%  2.511375        2.9

In [79]:
from sklearn.metrics import mean_absolute_error

In [81]:
mean_absolute_error(predictions['Actual'],predictions['Predicted'])

0.38862497126280937

In [83]:
predictions.describe()

         Actual  Predicted
count  1.000000        1.0
mean   2.511375        2.9
std         NaN        NaN
min    2.511375        2.9
25%    2.511375        2.9
50%    2.511375        2.9
75%    2.511375        2.9
max    2.511375        2.9

In [85]:
1.3942905791571905**0.5

1.1808008211197984

In [87]:
##The above value of 1.18080..... which is above the std signifies this model needs improvement

In [89]:
##Improving the model accuracy

In [91]:
#Creating new predictors via the player_past function

In [93]:
import numpy as np

def players_past(df):
    df = df.sort_values("Season")
    df["player_season"] = range(0,df.shape[0])
    
    df["war_corr"] = list(df[["player_season","WAR"]].expanding().corr().loc[(slice(None),"player_season"),"WAR"])
    df.loc[:, "war_corr"] = df["war_corr"].fillna(1)
    
    if 'war_diff' in df.columns:
        df.loc[df["war_diff"] == np.inf, "war_diff"] = 1
        df["war_diff"] = df["war_diff"].fillna(1)
    else:
        df["war_diff"] = 1  

    df.loc[:, "war_diff"] = df["war_diff"].fillna(1)
    return df

batting = batting.groupby("IDfg", group_keys=False, as_index=False).apply(players_past)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\983943490.py:19: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  batting = batting.groupby("IDfg", group_keys=False, as_index=False).apply(players_past)

In [95]:
def group_averages(df):
    return df["WAR"] / df["WAR"].mean()

In [97]:
batting["war_season"] = batting.groupby(by="Season", group_keys=False).apply(group_averages)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\3044964002.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  batting["war_season"] = batting.groupby(by="Season", group_keys=False).apply(group_averages)

In [99]:
new_predictors = predictors + ["player_season","war_season","war_diff","war_corr"]

In [101]:
fresh_predictions = backtest(batting,rr,new_predictors)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_13340\863576076.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[predictors] = train[predictors].fillna(train[predictors].mean())

In [103]:
fresh_predictions

       Actual  Predicted
75%  2.511375        2.9

In [117]:
mean_absolute_error(fresh_predictions["Actual"],fresh_predictions["Predicted"])

0.38862497126280937

In [121]:
import os
os.getcwd()

'C:\\Users\\Daniel'